// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://teeebalqimwaqonfnoaw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRlZWViYWxxaW13YXFvbmZub2F3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3NTAzMzQsImV4cCI6MjA2NTMyNjMzNH0.SExsVuYvzfuOgaP9VPpyFIX2smrEUwLG1p-BJ11zdl0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);